# Generated by Django 5.2.1 on 2025-05-09 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('anio_estreno', models.IntegerField(verbose_name='Año de estreno')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peliculas', to='cines.director')),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
                'ordering': ['titulo'],
            },
        ),
    ]
